services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # 1) volume de données pour la persistance
      - postgres_data:/var/lib/postgresql/data
      # 2) monte ton dossier sql/ directement dans le dossier d'init du conteneur
      - ./sql:/docker-entrypoint-initdb.d:ro     # ← RO = read‑only

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  postgres_data:
