version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      # 1) volume de données pour la persistance
      - postgres_data:/var/lib/postgresql/data
      # 2) monte ton dossier sql/ directement dans le dossier d'init du conteneur
      - ./sql:/docker-entrypoint-initdb.d:ro     # ← RO = read‑only

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"
  tiktok:
    build: ./services/tiktok
    container_name: tiktok
    depends_on:
      - rabbitmq
    ports:
     - "3002:3002"
    volumes:
     - ./shared:/shared
    command: sh -c "sleep 10 && npm start"
    environment:
    - AMQP_URL=amqp://user:password@rabbitmq

  twitch:
    build: ./services/twitch
    container_name: twitch
    depends_on:
      - rabbitmq
    ports:
     - "3001:3001"
    volumes:
     - ./shared:/shared
    command: sh -c "sleep 10 && npm start"
    environment:
    - AMQP_URL=amqp://user:password@rabbitmq

  youtube:
    build: ./services/youtube
    container_name: youtube
    depends_on:
      - rabbitmq
    ports:
     - "3003:3003"
    volumes:
    - ./shared:/shared
    command: sh -c "sleep 10 && npm start"
    environment:
    - AMQP_URL=amqp://user:password@rabbitmq


  consumer:
    build: ./consumer
    container_name: consumer
    depends_on:
      - rabbitmq
    ports:
     - "5000:5000"
    volumes:
     - ./certs:/certs
      
    command: sh -c "sleep 10 && npm start"

volumes:
  postgres_data:
